### ISSUE TITLE
Error in popup mode

### ISSUE THREAD

**Issue by glterica** [ailon/cropro#1]
Hello @ailon,

I'm getting a strange error when the cropper is set to popup mode:

![popup_case](https://user-images.githubusercontent.com/52828158/115765822-24f38a00-a39f-11eb-9e8e-876c30f7ed11.gif)

It seems to be coming from the popup resizing event. No errors in inline mode:

![inline_case](https://user-images.githubusercontent.com/52828158/115765912-3b014a80-a39f-11eb-8209-1a73dfe7ae86.gif)

Have you seen it before? Any suggestions on how to avoid it? The screenshots were taken with version 1.0.3, but the same happened when downgrading to 1.0.2.

Thanks!

p.s. It doesn't seem to affect the functionality of the tool, but I'd rather avoid getting errors in the console!

**Comment by ailon** [comment]
Hi,

Thank you for reporting this. I will investigate it today and release a fix or get back to you if I need additional details.

**Comment by ailon** [comment]
It should be fixed now in 1.0.4

**Comment by glterica** [comment]
Awesome, thank you!
