### ISSUE TITLE
Request: make `CropArea.render` public like in markerjs2

### ISSUE THREAD

**Issue by tarngerine** [ailon/cropro#11]
useful for grabbing the dataurl imperatively without doing startRenderAndClose and addRenderEventListener, so i can do something like

```
const dataurl = await cropArea.render();
```

**Comment by ailon** [comment]
Rendering has some side-effects (at the very least it's unzooming). So it wouldn't work to [re]render while still cropping.

**Comment by tarngerine** [comment]
Ah, I see. The use case I have is actually cropping without even showing the UI. Maybe best for me to just implement this in canvas manually.

The reason I was doing it is because I am allowing users to toggle back and forth between markerjs2 and cropro.

When you go from markerjs2 -> cropro, I create a non-user-visible MarkerArea that is uncropped with the original image source, use MarkerArea.render, and render out a full sized image with markers. This can then be used in cropro, so we preserve the original image size no matter how many times we go back and forth.

When you go from cropro -> markerjs2, I create a non-user-visible CropArea that has no markers, that can be used in markerjs2, so it can re-render the markers saved in MarkerAreaState (plus some offsets after the crop). This one I'm still using startRenderAndClose and was hoping to use render here.

But thanks for explaning, I can prob work around this :)
