### ISSUE TITLE
The crop area jumps unpredictably

### ISSUE THREAD

**Issue by milaabl** [ailon/cropro#13]
There's a major bug present both when integrating the plugin with different external codes and on the official markerjs2 and cropro plugin pages and on the Codesandbox projects linked to them.

I've attached the video capture of the issue. When I try to crop the image and change the crop area's borders, the bottom border starts to shift to top. It's strange and is very annoying when you're almost done with your perfectly cropped image and then everything just shifts and messes up, and you have to repeat the process over and over again.

[Video](https://www.dropbox.com/s/v2vklnirdy37u16/CROPRO%20-%20Popup%20mode%20demo%20-%20CodeSandbox%20-%20Google%20Chrome%202022-11-12%2022-02-21.mp4?dl=0)

Could you please fix that? I really enjoy using CROPRO, but the bug is the only obstacle to a perfectly-working library.

**Comment by ailon** [comment]
Hmm.. What version of Chrome is this? The whole behavior looks weird. Like when you go to the demos on markerjs.com and the demo is somehow shifted from the image and is above the site menu (which is not how I see it).

Could it be that you are running some browser extension that has this side-effect?

**Comment by ailon** [comment]
Yes, I was able to replicate this weird behavior. Seems to be happening when you are dragging the crop corner vertically (for some reason). Thank you for reporting this. I will look into it!

As a workaround you can disable the "zoom to selection" functionality (the magnifying glass button) for now.

**Comment by milaabl** [comment]
It looks like the CROPRO library reacts to the crop area border clicks as clicks on the image and it looks like it's calling 2 events at the same time: crop area change (resizing the crop area) and image move (changing the position of the image on the canvas).

**Comment by milaabl** [comment]
Same issue present on the popup demo: https://www.dropbox.com/s/mzzsry2cvmaa9hc/Open%20CROPRO%20in%20a%20popup%20_%20marker.js%20-%20Google%20Chrome%202022-11-14%2015-34-14.mp4?dl=0

**Comment by ailon** [comment]
Yes, I will look into it this week.

**Comment by milaabl** [comment]
Great! Thank you, seems to be working great now!
