### ISSUE TITLE
Using renderAtNaturalSize with flip actions causes a corrupted image

### ISSUE THREAD

**Issue by pull-tom** [ailon/cropro#14]
When utilising the renderAtNaturalSize setting, the flip actions (vertical and horizontal) produce a corrupted image. Rotating the image does not produce the same results and is unaffected.

Here is a CodeSandbox (forked from the original in the documentation, with renderAtNaturalSize being the only change):

https://codesandbox.io/s/cropro-customize-ui-demo-forked-cx8jxu?file=/src/index.js:150-169

**Comment by ailon** [comment]
Yes, I see the issue. Thank you for reporting it and the repro! I will look into it.

**Comment by ailon** [comment]
This should be fixed now in v1.2.2. Thank you for reporting, @pull-tom!
