### ISSUE TITLE
Blank image when image is rotated and cropped in iOS

### ISSUE THREAD

**Issue by Malli1320** [ailon/cropro#17]
getting blank image when image is rotate and cropped in iOS and sometimes it get stuck in editor with loading indicator keep processing in loop, once we rotate and crop the image.

**Comment by ailon** [comment]
Hi. I've played with it for a bit and couldn't reproduce the issue. Could you provide some more details/steps to reproduce? Do you experience the same on the demo page [here](https://markerjs.com/demos/cropro/all-defaults/)?

Also, if you see the spinner it feels like there should be some error in the browser's console.

**Comment by Malli1320** [comment]
Here is the link to reproduce the issue
@ailon https://codesandbox.io/p/sandbox/cropro-all-defaults-demo-forked-2lkll7?file=%2Fsrc%2Findex.js%3A16%2C4

steps to reproduce
1. click image
2. rotate 90 deg left or right
3. resize the crop rectangle on image
4. click save

**Comment by ailon** [comment]
Thanks, @Malli1320! I see the issue now. I will investigate and get back to you.

**Comment by ailon** [comment]
I've been trying to get to the bottom of this and here's where I am at this point:

Looks like Safari on iOS can't render images with `width * height` larger than 2^24 (or 16,777,216). When you rotate a large (non-square) image on the side and have `renderAtNaturalSize = true` it becomes larger than that and Safari craps out silently. A quick workaround would be to disable `renderAtNaturalSize` or set `renderWidth` and `renderHeight` manually. Would that work in your scenario?

I may just add some setting to enable "protection" from this issue by limiting the render size to that max value. I'm not very keen on either applying this across the board or doing some "dirty" user-agent Safari/iOS detection, though.

**Comment by Malli1320** [comment]
This is what we get for renderAtNaturalSize is enabled
![Screenshot_20231129_033832](https://github.com/ailon/cropro/assets/96905864/a3aac59c-82a9-4e5b-afb1-f6ba5a50f51f)

and this is for renderAtNaturalSize is disabled
![Screenshot_20231129_033752](https://github.com/ailon/cropro/assets/96905864/79f00746-7f79-4970-957f-2a59aaefacd5)

Even though if we set renderWidth and rendreHeight we will face the same issue as of now because we will set the original image height and width and again it will exceed the max value.
But in our case we want the cropped image with the original dimension as above when renderAtNaturalSize is enabled, so if we disable the renderAtNaturalSize then what should be the calculation to set proper renderHeight and renderWidth in such a way that we get the image without compromising the quality.

**Comment by ailon** [comment]
I will add a limiter that will take aspect ratio into account.

**Comment by Malli1320** [comment]
ok, still we need to disable renderAtNaturalSize after you set the limiter?

**Comment by ailon** [comment]
No, the plan is to add a setting that will be the max area size (eg. 2^24) and it will check if the resulting image fits and then downscale if it doesn't.

**Comment by ailon** [comment]
I've released v1.5.0 that should mitigate this issue. Set `cropArea.renderMaxSize = Math.pow(2, 24);` to limit the size to what iOS Safari can handle.
