### ISSUE TITLE
Close button doesnt work correctly

### ISSUE THREAD

**Issue by dtes** [ailon/cropro#2]
Hi. Looks like I found a little bug. When I click the close button close event listeners weren't fired. Perhaps you need to call method close() rather than closeUI().
https://github.com/ailon/cropro/blob/656367a643c75842a8a051fc681caad4a4b638ba/src/CropArea.ts#L932

**Comment by ailon** [comment]
Thanks! Just pushed a 1.0.5 update with the fix.
