### ISSUE TITLE
Rotate Reduces Resolution

### ISSUE THREAD

**Issue by 93786** [ailon/cropro#6]
There's no way to rotate an image and retain its resolution. So if you have an image that's 1000 x 500 and go from landscape to portrait, the height of the image will be 500. If you then eliminate the white space on the sides, it's now 250 x 500.

**Comment by ailon** [comment]
Use `renderAtNaturalSize` if you want to preserve the original resolution. More info [here](https://markerjs.com/docs/cropro/rendering-options).
