### ISSUE TITLE
iOS bug around resizing when switching from portrait to landscape back to portrait

### ISSUE THREAD

**Issue by tmigacz** [ailon/cropro#7]
This bug is specific only for iOS phones, and only when using Safari's "Add to Home Screen" feature. Note that the website needs to a [web app manifest file](https://web.dev/add-manifest/) to support the "Add to Home Screen" feature.

When using the cropping tool in portrait mode on your iOS phone, when you switch to landscape view, the height of the cropping tool is updated, but when you switch the phone back to portrait view, the height is not updated back. 

Steps to reproduce:

- Open your website in Safari on an iOS phone.
- Use the "Add to Home Screen" feature in Safari
- Open your web app from the Home Screen
- Open the cropping tool on your website with your phone in portrait view.
- Rotate your phone to switch to landscape view. The height of the cropping tool will be updated.
- Rotate your phone back to portrait view. The height of the cropping tool will NOT be updated.

Here's what it looks like when the height isn't properly updated (note half the screen is not covered by the cropping tool):

![image](https://user-images.githubusercontent.com/27440953/141802511-dc846b96-c1f6-4842-8dde-5d77c5afcab7.png)

**Comment by ailon** [comment]
Hey. Thank you for reporting this. I don't have access to an iOS device right now, will try to reproduce later. 

What is that underlying page? It looks like the whole thing isn't resized either. Or does it just end there?

**Comment by tmigacz** [comment]
Thanks for the quick response! 

The page just ends there. We tried it on a larger page with more content and it's only the cropping (and maker tool) that doesn't get resized.

**Comment by ailon** [comment]
Thank you for the details. I'll try to replicate this, but if it only happens when adding to home screen, it feels like a Safari bug. This shouldn't be any different than a normal browser window from the code's perspective.

In any case, feels like this is going to be painful to debug without a Mac :/

**Comment by tmigacz** [comment]
Agreed, but I still appreciate you taking a look.
